completed task
aiakimov/react-homeworks pull request #17
Opened 2022-05-15 15:19 UTC by aiakimov

2022-05-16 11:13 UTC, PaulVersAtile requested changes

2022-05-16 11:13 UTC, PaulVersAtile commented on src/Inputs.tsx
> +    type: Function
Не очень понятна идея параметра type здесь

2022-05-16 11:13 UTC, PaulVersAtile commented on src/Inputs.tsx
> +    }
Это можно узнать через e.target.name. Плюс у чекбокса состояние хранится в event.target.checked - на это обращалось внимание в условии задачи )

2022-05-16 11:13 UTC, PaulVersAtile commented on src/Inputs.tsx
> +    setFunc: React.Dispatch<React.SetStateAction<any>>,
setFunc это очень крутая идея

2022-05-16 11:13 UTC, PaulVersAtile commented on src/Inputs.tsx
> +    }
Также здесь произойдет замента типа для инпутов с type number и range. По умолчанию они number, но event.target.value у них строка. И если просто засетать это в стейт, то тип заменится

2022-05-16 15:50 UTC, aiakimov commented on src/Inputs.tsx
> +    type: Function
ну, на сколько я увидел в примере, у тебя в стейтах значения в определенных типах, где-то number, где-то string.. поэтому что бы в стейт не записывалась строка только я определяю типы зарание, с помощью аргумента type, в который передаю нужный конструктор)

2022-05-20 10:10 UTC, PaulVersAtile requested changes

2022-05-20 10:10 UTC, PaulVersAtile commented on src/Inputs.tsx
> +    }
У radio тоже нужно доставать значение через event.target.checked

2022-05-20 10:10 UTC, PaulVersAtile commented on src/Inputs.tsx
> +    type: Function
всё, доехал, у тебя type используется для преобразования типа на 26-й строчке. Ок, идея принимается)

2022-05-20 10:19 UTC, PaulVersAtile approved these changes

2022-05-20 15:57 UTC, merged