Task 22.1
aiakimov/react-homeworks pull request #18
Opened 2022-05-17 13:33 UTC by aiakimov

отрефакторил, точнее полностью переписал)

2022-05-28 18:49 UTC, PaulVersAtile requested changes

2022-05-28 18:49 UTC, PaulVersAtile commented on src/complexComponent/List.jsx
> +  };
Здесь в ифе с 26-й строчки по 29-ю и с 32-й по 34-ю абсолютно одинаковые строчки кода => тогда надо выносить в функцию.

2022-05-28 18:49 UTC, PaulVersAtile commented on src/complexComponent/List.jsx
> +  }, []);
Верно

2022-05-28 18:49 UTC, PaulVersAtile commented on src/complexComponent/List.jsx
> +    const amount = selectedHeroes.filter((el) => el === true).length;
Вот такие вычисления делаются через метод массива reduce

2022-05-29 07:00 UTC, aiakimov commented on src/complexComponent/List.jsx
> +    const amount = selectedHeroes.filter((el) => el === true).length;
это принципиально? ведь abknth filter тоже нужный массив возвращает)

2022-06-01 11:10 UTC, PaulVersAtile commented on src/complexComponent/List.jsx
> +    const amount = selectedHeroes.filter((el) => el === true).length;
Здесь принципиально, потому что итоговый результат, который тебе требуется - это число. Из массива нужно получить число. Фильтр - это когда из массива нужно выкинуть лишнее. 
`selectedHeroes.reduce((res, item) => item ? res + 1 : res, 0)`
`selectedHeroes.filter((el) => el === true).length`
Но твое решение реально короче

2022-06-01 11:11 UTC, PaulVersAtile approved these changes

2022-06-02 18:02 UTC, merged